demo1/urls.py
from django.urls import path
from demo1 import views
app_name = 'demo1'

urlpatterns = [
    path('user/', views.userview, name='user'),
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('login/', views.loginview, name='loginview'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.registeruserview, name='register'),
]

pro9/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('demo1.urls'))
]

demo1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class registermodel(User):
    li=[['MALE','Male'],['FEMALE','Female']]
    gender=models.CharField(max_length=30,choices=li)
    age=models.IntegerField()
    phone=models.BigIntegerField()
    

demo1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from demo1.models import registermodel
from django.contrib.auth.hashers import make_password


class NEWUSER(UserCreationForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','password1','password2','email']
        
        
class registerform(forms.ModelForm):
    password2=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=registermodel
        fields=['username','first_name','last_name','email','phone','gender','age','password']
    def save(self,commit=True):
        user=super(registerform,self).save(commit=False)
        user.password=make_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
        

demo1/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from demo1.forms import NEWUSER
from demo1.forms import registerform
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def userview(request):
    form = NEWUSER()
    if request.method == 'POST':
        form = NEWUSER(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/register/')
    return render(request, 'register.html', {'form': form})


def registeruserview(request):
    form = registerform()
    if request.method == 'POST':
        form = registerform(request.POST)
        if request.POST['password'] == request.POST['password2']:
            if form.is_valid():
                form.save()
                print("haii")
                return redirect('/login/')
    return render(request, 'register.html', {'form': form})


def loginview(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.cleaned_data['username']
            pass1 = form.cleaned_data['password']
            us = authenticate(username=user, password=pass1)
            if us is not None:
                login(request, us)
                print(us)
                return redirect('/home/')
    return render(request, 'login1.html', {'form': form})


def home(request):
    return render(request, 'home.html')


def logout_view(request):
    logout(request)
    return redirect('/home/')


def welcome(request):
    return render(request, 'welcome.html')

demo1/templates/login1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            background-color: #f2f2f2;
            font-family: Arial, sans-serif;
        }

        .login-container {
            width: 400px;
            margin: 0 auto;
            background-color: #fff;
            border: 1px solid #ccc;
            box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);
            padding: 20px;
        }

        h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            font-weight: bold;
            margin-bottom: 8px;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 12px 20px;
            margin-bottom: 20px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <div class="login-container">
        <h1>Welcome to Our App</h1>
        <form method="post">
            {%csrf_token%}
            {{form.username}}
            {{form.password}}
            <input type="submit" value="Log In">
        </form>
        <h4><a href="{% url 'demo1:register' %}" class="btn">Register</a></h4>

    </div>
</body>

</html>

demo1/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <style>
        body {
            background-color: #f2f2f2;
            font-family: Arial, sans-serif;
        }

        .register-container {
            width: 800px;
            margin: 0 auto;
            background-color: #fff;
            border: 1px solid #ccc;
            box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);
            padding: 20px;
        }

        h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            font-weight: bold;
            margin-bottom: 8px;
        }

        input[type="text"],
        input[type="email"],
        input[type="age"],
        input[type="gender"],
        input[type="number"],
        input[type="password"] {
            width: 100%;
            padding: 12px 20px;
            margin-bottom: 5px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        input[type="submit"] {
            background-color: #e45f1d;
            color: white;
            padding: 14px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .btn {
            display: block;
            width: 250px;
            margin: 0 auto;
            background-color: #5436e7;
            color: white;
            padding: 12px 18px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
        }


        .btn:hover {
            background-color: #4551a0;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
    </style>

</head>

<body>
    <div class="register-container">
        <h1>Welcome to Our App</h1>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Register">
        </form>
        <div>
            <h4><a href="{% url 'demo1:loginview' %}" class="btn">Login</a></h4>
        </div>
    </div>
</body>

</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <style>
        body {
            background-color: #f2f2f2;
            font-family: Arial, sans-serif;
        }

        .welcome-container {
            width: 400px;
            margin: 0 auto;
            background-color: #fff;
            border: 1px solid #ccc;
            box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);
            padding: 20px;
        }

        h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
        }

        p {
            font-size: 16px;
            line-height: 1.5;
            margin-bottom: 20px;
        }

        .btn {
            display: block;
            width: 200px;
            margin: 0 auto;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
        }

        .btn:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>

    <div class="welcome-container">
        <h1>Welcome to Our App</h1>
        {% if user.is_authenticated %}
        <h3> Haii Mr/Ms {{user.username|title}} </h3>
        <h4><a href="{% url 'demo1:logout' %}" class="btn">Logout</a></h4>

        {%else%}
        <h4><a href="{% url 'demo1:loginview' %}" class="btn">Login</a></h4>
        <h4><a href="{% url 'demo1:register' %}" class="btn">Register</a></h4>

        {% endif %}
        <p>Thank you for choosing our app. We hope you have a great experience using it.</p>
    </div>


</body>

</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome to welcome page</h1>
</body>
</html>